---
title: "Advent of Code 2022, Day 7"
author: "Skip Perry"
date: "December 2022"
output: github_document
---

```{r setup, message=FALSE}
options(dplyr.summarise.inform = FALSE)
library(tidyverse)
```

```{r}
df <- 
  read_lines("data/day7a.txt") |> 
  as_tibble() |> 
  mutate(
    value = str_remove(value, "\\$ "),
    cur_dir = NA_character_,
    file_name = NA_character_,
    file_size = NA_integer_
  )

df

for (i in 1:nrow(df)) {
  if (df$value[i] == "cd home") { df$cur_dir[i] <- "home" }
  else if (df$value[i] == "ls") { df$cur_dir[i] <- df$cur_dir[i-1] }
  else if (str_detect(df$value[i], "^dir ")) { df$cur_dir[i] <- df$cur_dir[i-1] }
  else if (str_detect(df$value[i], "^\\d+ ")) { 
    df$cur_dir[i] <- df$cur_dir[i-1] 
    df$file_name[i] <- str_remove(df$value[i], "\\d+")
    df$file_size[i] <- str_extract(df$value[i], "\\d+")
  }
  else if (str_detect(df$value[i], "^cd \\w+")) { 
    df$cur_dir[i] <- str_c(df$cur_dir[i-1], "/", str_extract(df$value[i], "\\w+$"))
  }
  else if (df$value[i] == "cd ..") { df$cur_dir[i] <- str_remove(df$cur_dir[i-1], "/\\w+$") }
}
```

```{r}
dir_sizes_tmp <- 
  df |> 
  mutate(file_size = replace_na(as.numeric(file_size), 0)) |> 
  arrange(cur_dir) |> 
  group_by(cur_dir) |> 
  summarize(dir_size = sum(file_size))
```

```{r}
dir_list <- dir_sizes_tmp |> pull(cur_dir)

get_full_dir_size <- function(dir_name) {
  dir_sizes_tmp |> 
    filter(str_detect(cur_dir, dir_name)) |> 
    summarize(dir_size = sum(dir_size)) |> 
    transmute(cur_dir = dir_name, dir_size)
}

dir_sizes <- map_dfr(dir_list, get_full_dir_size)
```

```{r}
dir_sizes |> 
  filter(dir_size < 100000) |> 
  summarize(sum(dir_size))
```

```{r}
dir_sizes |> 
  filter(dir_size > (30000000 - (70000000 - 42080344))) |> 
  arrange(dir_size)
```

